=== acm0173/1-DAM_LMGSI_Adri-n/TEMA11/Ejemplo4/clientes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="listaclientes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cliente" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"></xs:element>
                            <xs:element name="apellido" type="xs:string"></xs:element>
                            <xs:choice>
                                <xs:element name="dni" type="tipodni" ></xs:element>
                                <xs:element name="nie" type="xs:string"></xs:element>
                            </xs:choice>
                            <xs:element name="compras" type="tipocompras"></xs:element>
                            <xs:element name="regalo" type="xs:string" minOccurs="0"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="espaÃ±ol" type="xs:string" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <!-- TIPOS PERSONALIZADOS -->
<!-- longitud DNI -->
    <xs:simpleType name="tipodni">
        <xs:restriction base="xs:string">
            <xs:length value="9"></xs:length> <!-- lo escrito en el campo debe tener una longitud concreta -->



        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipocompras">
        <xs:restriction base="xs:integer"> 
            <xs:minInclusive value="3000"> </xs:minInclusive>
            <xs:maxInclusive value="5000"> </xs:maxInclusive>
        </xs:restriction>
    </xs:simpleType>




</xs:schema>

=== acm0173/1-DAM_LMGSI_Adri-n/TEMA11/Ejemplo2/clientes.xml
<?xml version="1.0" encoding="UTF-8"?>
<listaclientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="clientes.xsd">
    <cliente español="si">
        <nombre> Juan </nombre>
        <apellido> Sanchez </apellido>
        <dni>77883322P</dni>
        <compras>45000</compras>
        <regalo>bolsa deporte</regalo>
    </cliente>
    <cliente español="no">
        <nombre> Jose </nombre>
        <apellido> Diaz </apellido>
        <dni> 67839021A</dni>
        <compras> 45000 </compras>
    </cliente>
</listaclientes>
