<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE empleados [
    <!ELEMENT empleados (empleado+)>
    <!ELEMENT empleado (nombre, edad)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT edad (#PCDATA)>

    <!ATTLIST empleado sexo (y|h) #REQUIRED
    sueldo CDATA #IMPLIED> <!-- CData significa que haya que meter un texto e #IMPLIED significa que lo escrito ahí es opcional-->
]>

<empleados>
  <empleado sexo="y" sueldo="1800">
    <nombre>Alberto Ruiz</nombre>
    <edad>56</edad>
  </empleado>
  <empleado sexo="h" sueldo="1600">
    <nombre>Gloria Martín</nombre>
    <edad>35</edad>
  </empleado>
</empleados>